name: Create and publish Docker image

on:
  pull_request:
    types: [closed] 
    branches: 
      - main
  workflow_dispatch:

env:
  REGISTRY: ghrc.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      content: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{steps.metadata.outputs.tags}}
          labels: ${{steps.metadata.outputs.labes}}
